<?php
/**
 * OneOfProgramCurrencyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Tapfiliate\Sdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * My App
 *
 * This is an awesome app!
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Tapfiliate\Sdk;

use PHPUnit\Framework\TestCase;

/**
 * OneOfProgramCurrencyTest Class Doc Comment
 *
 * @category    Class
 * @description OneOfProgramCurrency
 * @package     Tapfiliate\Sdk
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OneOfProgramCurrencyTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "OneOfProgramCurrency"
     */
    public function testOneOfProgramCurrency()
    {
    }
}
