<?php
/**
 * ProgramApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Tapfiliate\Sdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * My App
 *
 * This is an awesome app!
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Tapfiliate\Sdk;

use Tapfiliate\Sdk\Configuration;
use Tapfiliate\Sdk\ApiException;
use Tapfiliate\Sdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProgramApiTest Class Doc Comment
 *
 * @category Class
 * @package  Tapfiliate\Sdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProgramApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getAListOfPrograms
     *
     * .
     *
     */
    public function testGetAListOfPrograms()
    {
    }
}
